[package]
name = "cani"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.8", features = ["derive"] }
dirs = "5.0.1"
reqwest = { version = "0.11.18", features = ["default-tls", "blocking"] }
serde = { version = "1.0.164", features = ["std", "derive"] }
serde_json = "1.0.99"
